name: CI CD Day 5 Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "Tests passed"

      - name: Build message
        run: echo "Build successful"

      - name: Build Docker image
        run: docker build -t day5-demo .

      - name: Login Docker Hub
        run: echo "${{ dckr_pat_-HzjZjfEtuXs_wMdUDzuD4ztw5U }}" | docker login -u "${{ keval2410 }}" --password-stdin

      - name: Tag image
        run: docker tag day5-demo ${{ keval2410 }}/day5-demo:latest

      - name: Push image
        run: docker push ${{ keval2410 }}/day5-demo:latest




  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy step
        run: |
          mkdir public
          cp -r app/* public/
          echo "Deployment done"
